title: Screensaver Documentation 
email: sean_erickson@hms.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  Screensaver HTS LIMS
  Open source software for high throughput screening management of 
  - plated compound libraries
  - HTS experiments
  - plated compound volumes
  - diluted plates 
baseurl: "/screensaver" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: seanderickson

aux_links:
  "Screensaver on GitHub":
    - "//github.com/hmsiccbl/screensaver"




# Build settings
#theme: just-the-docs 
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed


# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
